**Restaurantes**

url=https://datos.canarias.es/catalogos/general/dataset/establecimientos-de-restauracion-inscritos-en-el-registro-general-turistico-de-canarias

In [14]:
import pandas as pd

df = pd.read_csv(r"C:\Users\cgsos\Documents\Cuarto\TFG\FLICKR\datos\LLM\establecimientos-de-restauracion-inscritos-en-el-registro-general-turistico-de-canarias.csv",sep=";")

df_la_palma = df[df["direccion_isla_nombre"].str.strip().str.lower() == "la palma"]

df_la_palma.to_csv(r"C:\Users\cgsos\Documents\Cuarto\TFG\FLICKR\datos\LLM\la_palma_ocio\dirty_dataset\restauracion_la_palma_sucio.csv", index=False, sep=";")

print("✔ Archivo generado")
print("Total registros:", len(df_la_palma))

✔ Archivo generado
Total registros: 804

In [17]:
import pandas as pd
import urllib.parse

df = pd.read_csv(
    r"C:\Users\cgsos\Documents\Cuarto\TFG\FLICKR\datos\LLM\la_palma_ocio\dirty_dataset\restauracion_la_palma_sucio.csv",
    sep=";"
)

df = df.rename(columns={
    "direccion_municipio": "municipio",
    "establecimiento_nombre_comercial": "nombre",
    "establecimiento_grupo": "grupo"
})

df["municipio"] = df["municipio"].astype(str).str.strip()
df["nombre"] = df["nombre"].astype(str).str.strip()
df["grupo"] = df["grupo"].astype(str).str.strip()


df = df[df["municipio"] != "_U"]

def maps_url(nombre, municipio):
    q = urllib.parse.quote(f"{nombre} {municipio} La Palma")
    return f"https://www.google.com/maps/search/{q}"

rows = []

for municipio, sub in df.groupby("municipio"):
    sub_unique = sub.drop_duplicates(subset=["nombre"])
    seleccion = sub_unique.head(2)

    for _, row in seleccion.iterrows():
        rows.append({
            "municipio": municipio,
            "nombre": row["nombre"],
            "grupo": row["grupo"],
            "url_maps": maps_url(row["nombre"], municipio)
        })

restaurantes = pd.DataFrame(rows).sort_values(["municipio", "nombre"])

restaurantes

,municipio,nombre,grupo,url_maps
1,Barlovento,El Ideal,Bar-Cafeteria,https://www.google.com/maps/search/El%20Ideal%...
0,Barlovento,Juventud Norteña,Bar-Cafeteria,https://www.google.com/maps/search/Juventud%20...
2,Breña Alta,Teneguia,Bar-Cafeteria,https://www.google.com/maps/search/Teneguia%20...
3,Breña Alta,Venezuela,Bar-Cafeteria,https://www.google.com/maps/search/Venezuela%2...
4,Breña Baja,Juventud Española,Bar-Cafeteria,https://www.google.com/maps/search/Juventud%20...
5,Breña Baja,Paris,Bar-Cafeteria,https://www.google.com/maps/search/Paris%20Bre...
6,El Paso,Bocaccio,Bar-Cafeteria,https://www.google.com/maps/search/Bocaccio%20...
7,El Paso,Cumbre,Bar-Cafeteria,https://www.google.com/maps/search/Cumbre%20El...
9,Fuencaliente De La Palma,La Cantina Del Gladiador,Bar-Cafeteria,https://www.google.com/maps/search/La%20Cantin...
8,Fuencaliente De La Palma,Los Amigos Juan Petra,Bar-Cafeteria,https://www.google.com/maps/search/Los%20Amigo...
10,Garafia,Baltasar Martín,Bar-Cafeteria,https://www.google.com/maps/search/Baltasar%20...
11,Garafia,Taberna Santi,Bar-Cafeteria,https://www.google.com/maps/search/Taberna%20S...
12,Los Llanos De Aridane,Avenida,Bar-Cafeteria,https://www.google.com/maps/search/Avenida%20L...
13,Los Llanos De Aridane,Galicia,Bar-Cafeteria,https://www.google.com/maps/search/Galicia%20L...
14,Puntagorda,Cuatro Caminos,Bar-Cafeteria,https://www.google.com/maps/search/Cuatro%20Ca...
15,Puntagorda,El Roque,Bar-Cafeteria,https://www.google.com/maps/search/El%20Roque%...
16,Puntallana,El Rincón,Bar-Cafeteria,https://www.google.com/maps/search/El%20Rinc%C...
17,Puntallana,La Unión,Bar-Cafeteria,https://www.google.com/maps/search/La%20Uni%C3...
18,San Andres Y Sauces,Del Puerto,Bar-Cafeteria,https://www.google.com/maps/search/Del%20Puert...
19,San Andres Y Sauces,Miami,Bar-Cafeteria,https://www.google.com/maps/search/Miami%20San...
21,Santa Cruz De La Palma,La Esquina,Bar-Cafeteria,https://www.google.com/maps/search/La%20Esquin...
20,Santa Cruz De La Palma,La Peña,Bar-Cafeteria,https://www.google.com/maps/search/La%20Pe%C3%...
23,Tazacorte,Avenida,Bar-Cafeteria,https://www.google.com/maps/search/Avenida%20T...
22,Tazacorte,Tigotán,Bar-Cafeteria,https://www.google.com/maps/search/Tigot%C3%A1...
24,Tijarafe,Alberto,Bar-Cafeteria,https://www.google.com/maps/search/Alberto%20T...
25,Tijarafe,Canarias,Bar-Cafeteria,https://www.google.com/maps/search/Canarias%20...
26,Villa De Mazo,Central,Bar-Cafeteria,https://www.google.com/maps/search/Central%20V...
27,Villa De Mazo,Puente Roto,Bar-Cafeteria,https://www.google.com/maps/search/Puente%20Ro...

In [4]:
restaurantes.to_csv(r"C:\Users\cgsos\Documents\Cuarto\TFG\FLICKR\datos\LLM\la_palma_ocio\clean_dataset\restaurantes_la_palma.csv", index=False, encoding="utf-8")

**Alojamientos**

url = https://datos.canarias.es/catalogos/general/dataset/?q=alojamientos+canarias&sort=score+desc%2C+metadata_modified+desc&page=2

In [1]:
import pandas as pd

df = pd.read_csv(r"C:\Users\cgsos\Documents\Cuarto\TFG\FLICKR\datos\LLM\alojamientos_declarados_a_la_candidatura_canaria.csv")

df_la_palma = df[df["nom_isla"].str.strip().str.upper() == "LA PALMA"]

print("Total alojamientos:", len(df_la_palma))

df_la_palma.to_csv(r"C:\Users\cgsos\Documents\Cuarto\TFG\FLICKR\datos\LLM\la_palma_ocio\dirty_dataset\alojamientos_la_palma_sucio.csv", index=False)

Total alojamientos: 242

In [5]:
import pandas as pd

df = pd.read_csv(
    r"C:\Users\cgsos\Documents\Cuarto\TFG\FLICKR\datos\LLM\la_palma_ocio\dirty_dataset\alojamientos_la_palma_sucio.csv",
    sep=",",
    engine="python",
    on_bad_lines="skip"
)

df = df.rename(columns={
    "nom_municipio": "municipio",
    "etiqueta": "nombre",
    "nom_tipo": "tipo",
    "nom_categor": "categoria"
})

nuevos = pd.DataFrame([{
    col: None for col in df.columns
} for _ in range(2)])

nuevos.loc[0, "municipio"] = "Garafía"
nuevos.loc[0, "nombre"] = "Casa La Fuente Garafía"
nuevos.loc[0, "tipo"] = "Vivienda Vacacional"
nuevos.loc[0, "categoria"] = "Rural"

nuevos.loc[1, "municipio"] = "Garafía"
nuevos.loc[1, "nombre"] = "Casa Los Hondos Garafía"
nuevos.loc[1, "tipo"] = "Vivienda Vacacional"
nuevos.loc[1, "categoria"] = "Rural"

# Añadir un alojamiento real para Puntallana
nuevos.loc[2, "municipio"] = "Puntallana"
nuevos.loc[2, "nombre"] = "Casa Rural Los Melindros"
nuevos.loc[2, "tipo"] = "Casa Rural"
nuevos.loc[2, "categoria"] = "Rural"

# Añadir otro alojamiento real para Puntallana
nuevos.loc[3, "municipio"] = "Puntallana"
nuevos.loc[3, "nombre"] = "Casa Rural Doña Herminia"
nuevos.loc[3, "tipo"] = "Casa Rural"
nuevos.loc[3, "categoria"] = "Rural"

df_actualizado = pd.concat([df, nuevos], ignore_index=True)

ruta_salida = r"C:\Users\cgsos\Documents\Cuarto\TFG\FLICKR\datos\LLM\la_palma_ocio\dirty_dataset\alojamientos_la_palma_sucio_actualizado.csv"
df_actualizado.to_csv(ruta_salida, index=False)

print("CSV sucio actualizado guardado en:")
print(ruta_salida)

CSV sucio actualizado guardado en:
C:\Users\cgsos\Documents\Cuarto\TFG\FLICKR\datos\LLM\la_palma_ocio\dirty_dataset\alojamientos_la_palma_sucio_actualizado.csv

In [6]:
import pandas as pd
import urllib.parse

df = pd.read_csv(
    r"C:\Users\cgsos\Documents\Cuarto\TFG\FLICKR\datos\LLM\la_palma_ocio\dirty_dataset\alojamientos_la_palma_sucio_actualizado.csv",
    sep=",",
    engine="python",
    on_bad_lines="skip"
)

df = df.rename(columns={
    "nom_municipio": "municipio",
    "etiqueta": "nombre",
    "nom_tipo": "tipo",
    "nom_categor": "categoria"
})

df["municipio"] = df["municipio"].astype(str).str.strip()
df["nombre"] = df["nombre"].astype(str).str.strip()
df["tipo"] = df["tipo"].astype(str).str.strip()
df["categoria"] = df["categoria"].astype(str).str.strip()

df["municipio"] = df["municipio"].str.replace("ń", "ñ", regex=False)

df = df[~df["municipio"].isin(["Breńa Alta", "Breńa Baja"])]

def maps_url(nombre, municipio):
    q = urllib.parse.quote(f"{nombre} {municipio} La Palma")
    return f"https://www.google.com/maps/search/{q}"

rows = []

for municipio, sub in df.groupby("municipio"):
    sub_unique = sub.drop_duplicates(subset=["nombre"])
    seleccion = sub_unique.head(2)

    for _, row in seleccion.iterrows():
        rows.append({
            "municipio": municipio,
            "nombre": row["nombre"],
            "tipo": row["tipo"],
            "url_maps": maps_url(row["nombre"], municipio)
        })


alojamientos_limpio = pd.DataFrame(rows).sort_values(["municipio", "nombre"])

alojamientos_limpio

,municipio,nombre,tipo,url_maps
0,Barlovento,HOTEL LA PALMA ROMANTICA,Hotel,https://www.google.com/maps/search/HOTEL%20LA%...
2,Breña Alta,APARTAMENTOS LOS MORALES,Apartamentos,https://www.google.com/maps/search/APARTAMENTO...
1,Breña Alta,APARTAMENTOS MIRANDA,Apartamentos,https://www.google.com/maps/search/APARTAMENTO...
4,Breña Baja,HOTEL H10 TABURIENTE PLAYA,Hotel,https://www.google.com/maps/search/HOTEL%20H10...
3,Breña Baja,PARADOR NACIONAL DE LA PALMA,Hotel,https://www.google.com/maps/search/PARADOR%20N...
5,El Paso,APARTAMENTOS CASA DE LAS PALMERAS,Apartamentos,https://www.google.com/maps/search/APARTAMENTO...
6,El Paso,APARTAMENTOS HERMOSILLA,Apartamentos,https://www.google.com/maps/search/APARTAMENTO...
8,Fuencaliente,HOTEL LA PALMA & TENEGUÍA PRINCESS,Hotel,https://www.google.com/maps/search/HOTEL%20LA%...
7,Fuencaliente,PENSION CENTRAL,Hotel,https://www.google.com/maps/search/PENSION%20C...
9,Fuencaliente de La Palma,HOTEL LA PALMA PRINCESS,Hotel,https://www.google.com/maps/search/HOTEL%20LA%...
10,Fuencaliente de La Palma,PENSION CENTRAL,Hotel,https://www.google.com/maps/search/PENSION%20C...
11,Garafía,Casa La Fuente Garafía,Vivienda Vacacional,https://www.google.com/maps/search/Casa%20La%2...
12,Garafía,Casa Los Hondos Garafía,Vivienda Vacacional,https://www.google.com/maps/search/Casa%20Los%...
14,Los Llanos de Aridane,HOTEL EDEN,Hotel,https://www.google.com/maps/search/HOTEL%20EDE...
13,Los Llanos de Aridane,HOTEL VALLE ARIDANE,Hotel,https://www.google.com/maps/search/HOTEL%20VAL...
15,Puntagorda,PENSION MAR Y MONTE,Hotel,https://www.google.com/maps/search/PENSION%20M...
17,Puntallana,Casa Rural Doña Herminia,Casa Rural,https://www.google.com/maps/search/Casa%20Rura...
16,Puntallana,Casa Rural Los Melindros,Casa Rural,https://www.google.com/maps/search/Casa%20Rura...
19,San Andrés y Sauces,PENSION LAS LONJAS,Hotel,https://www.google.com/maps/search/PENSION%20L...
18,San Andrés y Sauces,PENSION RESIDENCIA EL DRAGO,Hotel,https://www.google.com/maps/search/PENSION%20R...
20,Santa Cruz de La Palma,HOTEL CASTILLETE,Hotel,https://www.google.com/maps/search/HOTEL%20CAS...
21,Santa Cruz de La Palma,PENSION LA CUBANA,Hotel,https://www.google.com/maps/search/PENSION%20L...
23,Tazacorte,APARTAMENTOS ISA TAZACORTE,Apartamentos,https://www.google.com/maps/search/APARTAMENTO...
22,Tazacorte,APARTAMENTOS MORROSOL,Apartamentos,https://www.google.com/maps/search/APARTAMENTO...
24,Tijarafe,APARTAMENTOS VISTA HERMOSA I,Apartamentos,https://www.google.com/maps/search/APARTAMENTO...
25,Villa de Mazo,HOTEL ARMINDA,Hotel,https://www.google.com/maps/search/HOTEL%20ARM...

In [7]:
alojamientos_limpio.to_csv(r"C:\Users\cgsos\Documents\Cuarto\TFG\FLICKR\datos\LLM\la_palma_ocio\clean_dataset\alojamientos_la_palma.csv", index=False)