In [ ]:
import pandas as pd

df = pd.read_csv(r"C:\Users\cgsos\Documents\Cuarto\TFG\FLICKR\datos\LLM\establecimientos-de-restauracion-inscritos-en-el-registro-general-turistico-de-canarias.csv",sep=";")

df_grancanaria = df[df["direccion_isla_nombre"].str.strip().str.lower() == "gran canaria"]

df_grancanaria.to_csv(r"C:\Users\cgsos\Documents\Cuarto\TFG\FLICKR\datos\LLM\grancanaria_ocio\dirty_dataset\restaurantes_gran_canaria_sucio.csv", index=False, sep=";")

print("✔ Archivo generado")
print("Total registros de Gran Canaria:", len(df_grancanaria))

**RESTAURANTES**

url = https://datos.canarias.es/catalogos/general/dataset/establecimientos-de-restauracion-inscritos-en-el-registro-general-turistico-de-canarias

In [45]:
import pandas as pd
import urllib.parse

df = pd.read_csv(r"C:\Users\cgsos\Documents\Cuarto\TFG\FLICKR\datos\LLM\grancanaria_ocio\dirty_dataset\restaurantes_gran_canaria_sucio.csv")

df["municipio"] = df["municipio"].astype(str).str.strip()
df["nombre"] = df["nombre"].astype(str).str.strip()
df["grupo"] = df["grupo"].astype(str).str.strip()

df = df[df["municipio"] != "_U"]

def maps_url(nombre, municipio):
    q = urllib.parse.quote(f"{nombre} {municipio} Gran Canaria")
    return f"https://www.google.com/maps/search/{q}"

rows = []

for municipio, sub in df.groupby("municipio"):
    sub_unique = sub.drop_duplicates(subset=["nombre"])
    seleccion = sub_unique.head(2)

    for _, row in seleccion.iterrows():
        rows.append({
            "municipio": municipio,
            "nombre": row["nombre"],
            "grupo": row["grupo"],
            "url_maps": maps_url(row["nombre"], municipio)
        })

restaurantes = pd.DataFrame(rows)
restaurantes = restaurantes.sort_values(["municipio", "nombre"])

restaurantes

,municipio,nombre,grupo,url_maps
1,Agaete,Casa Lolo,Bar-Cafeteria,https://www.google.com/maps/search/Casa%20Lolo...
0,Agaete,Ragú,Bar-Cafeteria,https://www.google.com/maps/search/Rag%C3%BA%2...
2,Aguimes,Del Pino,Bar-Cafeteria,https://www.google.com/maps/search/Del%20Pino%...
3,Aguimes,Peña,Bar-Cafeteria,https://www.google.com/maps/search/Pe%C3%B1a%2...
5,Artenara,"Cuevita, La",Bar-Cafeteria,https://www.google.com/maps/search/Cuevita%2C%...
4,Artenara,Diaz,Bar-Cafeteria,https://www.google.com/maps/search/Diaz%20Arte...
7,Arucas,Benjamin,Bar-Cafeteria,https://www.google.com/maps/search/Benjamin%20...
6,Arucas,Cafeteria Churreria Los Sifones,Bar-Cafeteria,https://www.google.com/maps/search/Cafeteria%2...
8,Firgas,Santana,Bar-Cafeteria,https://www.google.com/maps/search/Santana%20F...
9,Firgas,Taberna Aleman,Bar-Cafeteria,https://www.google.com/maps/search/Taberna%20A...
11,Galdar,El Puente,Bar-Cafeteria,https://www.google.com/maps/search/El%20Puente...
10,Galdar,Sushimi Galdar,Bar-Cafeteria,https://www.google.com/maps/search/Sushimi%20G...
13,Ingenio,"Gran Sol, El",Bar-Cafeteria,https://www.google.com/maps/search/Gran%20Sol%...
12,Ingenio,Yo-Ya,Bar-Cafeteria,https://www.google.com/maps/search/Yo-Ya%20Ing...
14,La Aldea De San Nicolas,Felix,Bar-Cafeteria,https://www.google.com/maps/search/Felix%20La%...
15,La Aldea De San Nicolas,Oliva,Bar-Cafeteria,https://www.google.com/maps/search/Oliva%20La%...
16,Las Palmas De Gran Canaria,Churreria-Chocolateria Los Angeles-Nazak Kebap...,Bar-Cafeteria,https://www.google.com/maps/search/Churreria-C...
17,Las Palmas De Gran Canaria,Tadeo,Bar-Cafeteria,https://www.google.com/maps/search/Tadeo%20Las...
19,Mogan,Cobana,Bar-Cafeteria,https://www.google.com/maps/search/Cobana%20Mo...
18,Mogan,Stop,Bar-Cafeteria,https://www.google.com/maps/search/Stop%20Moga...
20,Moya,Pizzeria Ca'Masita,Bar-Cafeteria,https://www.google.com/maps/search/Pizzeria%20...
21,Moya,"Tilos, Los",Bar-Cafeteria,https://www.google.com/maps/search/Tilos%2C%20...
22,San Bartolome De Tirajana,"Cafetin, El",Bar-Cafeteria,https://www.google.com/maps/search/Cafetin%2C%...
23,San Bartolome De Tirajana,"Garage, El",Bar-Cafeteria,https://www.google.com/maps/search/Garage%2C%2...
25,Santa Brigida,Pluma,Bar-Cafeteria,https://www.google.com/maps/search/Pluma%20San...
24,Santa Brigida,"Ramal, El",Bar-Cafeteria,https://www.google.com/maps/search/Ramal%2C%20...
26,Santa Lucia De Tirajana,"Sarten, La",Bar-Cafeteria,https://www.google.com/maps/search/Sarten%2C%2...
27,Santa Lucia De Tirajana,Verde,Bar-Cafeteria,https://www.google.com/maps/search/Verde%20San...
29,Santa Maria De Guia De Gran Canaria,"7, El",Bar-Cafeteria,https://www.google.com/maps/search/7%2C%20El%2...
28,Santa Maria De Guia De Gran Canaria,La Tasquita De Mateo,Bar-Cafeteria,https://www.google.com/maps/search/La%20Tasqui...
30,Tejeda,El Cairete,Bar-Cafeteria,https://www.google.com/maps/search/El%20Cairet...
31,Tejeda,Sombra Del Nublo,Bar-Cafeteria,https://www.google.com/maps/search/Sombra%20De...
32,Telde,"Punto-Ca'Patricia, El",Bar-Cafeteria,https://www.google.com/maps/search/Punto-Ca%27...
33,Telde,"Sobrino, El",Bar-Cafeteria,https://www.google.com/maps/search/Sobrino%2C%...
35,Teror,Bar Paco,Bar-Cafeteria,https://www.google.com/maps/search/Bar%20Paco%...
34,Teror,Nuevo Iris,Bar-Cafeteria,https://www.google.com/maps/search/Nuevo%20Iri...
36,Valleseco,La Herradura,Bar-Cafeteria,https://www.google.com/maps/search/La%20Herrad...
37,Valleseco,Mi Cielo,Bar-Cafeteria,https://www.google.com/maps/search/Mi%20Cielo%...
39,Valsequillo De Gran Canaria,"Cañas, Las",Bar-Cafeteria,https://www.google.com/maps/search/Ca%C3%B1as%...
38,Valsequillo De Gran Canaria,"Corderita, La",Bar-Cafeteria,https://www.google.com/maps/search/Corderita%2...
41,Vega San Mateo,Mallow,Bar-Cafeteria,https://www.google.com/maps/search/Mallow%20Ve...
40,Vega San Mateo,Marrero,Bar-Cafeteria,https://www.google.com/maps/search/Marrero%20V...

In [11]:
restaurantes.to_csv(r"C:\Users\cgsos\Documents\Cuarto\TFG\FLICKR\datos\LLM\grancanaria_ocio\clean_dataset\restaurantes_gran_canaria.csv", index=False, encoding="utf-8")

**ALOJAMIENTOS**


url = https://datos.canarias.es/catalogos/general/dataset/?q=alojamientos+canarias&sort=score+desc%2C+metadata_modified+desc&page=2

In [ ]:
import pandas as pd

df = pd.read_csv(r"C:\Users\cgsos\Documents\Cuarto\TFG\FLICKR\datos\LLM\alojamientos_declarados_a_la_candidatura_canaria.csv")

df_grancanaria = df[df["nom_isla"].str.strip().str.upper() == "Gran Canaria"]

print("Total alojamientos en gran canaria:", len(df_grancanaria))

df_grancanaria.to_csv(r"C:\Users\cgsos\Documents\Cuarto\TFG\FLICKR\datos\LLM\grancanaria_ocio\dirty_dataset\alojamientos_gran_canaria_sucio.csv", index=False)

In [46]:
import pandas as pd
import urllib.parse

df = pd.read_csv(
    r"C:\Users\cgsos\Documents\Cuarto\TFG\FLICKR\datos\LLM\grancanaria_ocio\dirty_dataset\alojamientos_gran_canaria_sucio.csv"
)

df["nom_municipio"] = df["nom_municipio"].astype(str).str.strip()
df["etiqueta"] = df["etiqueta"].astype(str).str.strip()

def maps_url(nombre, municipio):
    q = urllib.parse.quote(f"{nombre} {municipio} Gran Canaria")
    return f"https://www.google.com/maps/search/{q}"

rows = []

for municipio, sub in df.groupby("nom_municipio"):
    sub_unique = sub.drop_duplicates(subset=["etiqueta"])

    seleccion = sub_unique.head(2)

    for _, row in seleccion.iterrows():
        rows.append({
            "municipio": municipio,
            "nombre": row["etiqueta"],
            "tipo": row["nom_tipo"] if pd.notna(row["nom_tipo"]) else "Alojamiento",
            "url_maps": maps_url(row["etiqueta"], municipio)
        })

alojamientos = pd.DataFrame(rows)
alojamientos = alojamientos.sort_values(["municipio", "nombre"])

alojamientos

,municipio,nombre,tipo,url_maps
1,Agaete,HOTEL OCCIDENTAL ROCA NEGRA,Hotel,https://www.google.com/maps/search/HOTEL%20OCC...
0,Agaete,HOTEL PUERTO DE LAS NIEVES,Hotel,https://www.google.com/maps/search/HOTEL%20PUE...
2,Agüimes,HOTEL PLAYA DE ARINAGA,Hotel,https://www.google.com/maps/search/HOTEL%20PLA...
3,Artenara,Los Mojones Artenara,Vivienda vacacional,https://www.google.com/maps/search/Los%20Mojon...
4,Arucas,Hotel Rural La Hacienda del Buen Suceso,Hotel Rural,https://www.google.com/maps/search/Hotel%20Rur...
5,Firgas,Acoran Family Guest House,Casa de huéspedes,https://www.google.com/maps/search/Acoran%20Fa...
6,Galdar,HOTEL HACIENDA DE ANZO - STIKO SANALI,Hotel,https://www.google.com/maps/search/HOTEL%20HAC...
7,Ingenio,Villa Néstor,Bed & Breakfast,https://www.google.com/maps/search/Villa%20N%C...
9,La Aldea de San Nicolás,HOTEL LA ALDEA SUITES,Hotel,https://www.google.com/maps/search/HOTEL%20LA%...
8,La Aldea de San Nicolás,HOTEL LOS CASCAJOS,Hotel,https://www.google.com/maps/search/HOTEL%20LOS...
11,Las Palmas de Gran Canaria,HOTEL AC IBERIA LAS PALMAS,Hotel,https://www.google.com/maps/search/HOTEL%20AC%...
10,Las Palmas de Gran Canaria,HOTEL ASTORIA,Hotel,https://www.google.com/maps/search/HOTEL%20AST...
12,Mogán,APARTAMENTOS NIDO DEL AGUILA,Apartamentos,https://www.google.com/maps/search/APARTAMENTO...
13,Mogán,APARTAMENTOS TIHUYA,Apartamentos,https://www.google.com/maps/search/APARTAMENTO...
14,Moya,Dreamsea Boutique Experience,Hotel Boutique,https://www.google.com/maps/search/Dreamsea%20...
15,San Bartolomé de Tirajana,HOTEL COSTA CANARIA & SPA.,Hotel,https://www.google.com/maps/search/HOTEL%20COS...
16,San Bartolomé de Tirajana,HOTEL NEW FOLIAS,Hotel,https://www.google.com/maps/search/HOTEL%20NEW...
17,Santa Brígida,HOTEL ESCUELA SANTA BRIGIDA,Hotel,https://www.google.com/maps/search/HOTEL%20ESC...
18,Santa Lucía de Tirajana,ELBA VECINDARIO AEROPUERTO,Hotel,https://www.google.com/maps/search/ELBA%20VECI...
19,Santa Lucía de Tirajana,HOTEL AVENIDA DE CANARIAS,Hotel,https://www.google.com/maps/search/HOTEL%20AVE...
20,Santa María de Guía,Casa Verde de Guía,Casa Rural,https://www.google.com/maps/search/Casa%20Verd...
21,Tejeda,PARADOR CRUZ DE TEJEDA,Hotel,https://www.google.com/maps/search/PARADOR%20C...
22,Telde,HOSTAL ALBACAR,Hotel,https://www.google.com/maps/search/HOSTAL%20AL...
23,Teror,Hotel El Pino,Hotel,https://www.google.com/maps/search/Hotel%20El%...
24,Valleseco,La Casita de Abuela Paula,Casa Rural,https://www.google.com/maps/search/La%20Casita...
25,Valsequillo,La Vedette Villa Margarita,Villa vacacional,https://www.google.com/maps/search/La%20Vedett...
27,Vega de San Mateo,Casa Rural El Pajar de Miguel Velázquez,Casa Rural,https://www.google.com/maps/search/Casa%20Rura...
26,Vega de San Mateo,Hotel Rural Las Calas,Hotel Rural,https://www.google.com/maps/search/Hotel%20Rur...

In [38]:
alojamientos.to_csv(r"C:\Users\cgsos\Documents\Cuarto\TFG\FLICKR\datos\LLM\grancanaria_ocio\clean_dataset\alojamientos_gran_canaria.csv", index=False, encoding="utf-8")